### ISSUE TITLE
Excute Command "node custom_forms" Is not able to take the Var Request 

### ISSUE THREAD

**Issue by NeelRedyy** [kreta99/QS-Custom-Forms#1]
Hi, 
I have followed all the steps provided In the Page but the "node custom_forms" command Is unable to take the Var Request " Cannot find Module Request " 

Module.js: 549 Throw Err; 

We are stuck here after completing all the process can you please help us to resolve the Issue. 

Thank you, 
Neel

**Comment by kreta99** [comment]
Hi Neel, 

this is nodejs module. Installation guide updated to provide more clarity on this.

Best
Robert
